#!/bin/bash
# cancel-call-difftool

function check_repo() {
    repo_path=`git rev-parse --show-toplevel 2>/dev/null`
    if [[ $? -gt 0 ]]; then
        echo -e "⚠️  No git repo found."
        return 1
    else
        cd $repo_path
    fi
}

function cancel_call_difftool {
    sed -i '' '/# need_difftool/d' .git/hooks/pre-commit
}

check_repo && cancel_call_difftool